### ISSUE TITLE
bibfile not recognized in MWE

### ISSUE THREAD

**Issue by kuriwaki** [CoryMcCartan/cmc-article#4]
I'm probably doing something wrong but the minimal version of what I attempt does not recognize the bibfile.  Attached is a zipfile of the attempt, and below is what I do:

paper.qmd is 

```
---
title: "Title"
format:
  cmc-article-pdf: default
bibliography: references.bib
---

Body of paper. Citations are easy to use [@metropolis1953].
  
``` 

The notification I get is:

```
generating bibliography
  This is BibTeX, Version 0.99d (TeX Live 2022)
  The top-level auxiliary file: paper.aux
  The style file: apalike.bst
  I found no \bibdata command---while reading file paper.aux
  Warning--I didn't find a database entry for "metropolis1953"
  (There was 1 error message)

```
 I created this by running `quarto add CoryMcCartan/cmc-article`. Do I need a `header.tex` file or something else?
 
Replication:  [Archive.zip](https://github.com/CoryMcCartan/cmc-article/files/13193187/Archive.zip)

**Comment by CoryMcCartan** [comment]
Yeah, this is a limitation of the template—you either need to have appendix sections (marked as `# Section title {.appendix}`) OR you need to explicitly place the references section with
```
::: {#refs}
:::
```
at the end of the doc or whatever.  The usual quarto latex templates automatically put the references at the end of the doc (including after appendices) no matter what, but if you want appendices after references I haven't figured out a way to automatically insert the references section yet.

So if you're doing a template for someone I think putting the explicit references code above would be the way to go, along with commenting it to explain that it's special code that needs to stay there.

**Comment by kuriwaki** [comment]
thanks- the explicit placement will work fine.
